### PR TITLE
Fix admin page

### LINKED ISSUE #12: Admin page must be reloaded to view WYSIWYG-editor

### PR DESCRIPTION
**Pull request by JuulArthur**
Fix #12 #13

### CODE REVIEW

File: frontend/app/components/AdminView.js [hunk 1]
```diff
@@ -7,7 +7,8 @@ var AdminActions = require('../actions/AdminActions')
 
 function getState() {
     return {
-        feedback: AdminStore.getFeedback
+        feedback: AdminStore.getFeedback(),
+        conten: ""
```
Comment (hanskhe) [inline frontend/app/components/AdminView.js:11]: content?

File: frontend/app/components/AdminView.js [hunk 2]
```diff
@@ -17,41 +18,65 @@ var AdminView = React.createClass({
         this.setState(getState());
     },
     getInitialState: function () {
-        return {feedback: ''};
+        return {feedback: '', content: ''};
```
Comment (hanskhe) [inline frontend/app/components/AdminView.js:21]: content or conten??? Breaking bug?
